[window]
padding = { x = 3, y = 3 }
opacity = 1.0
decorations = "Full"
dynamic_title = false

[font]
size = 14.0
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

[env]
TERM = "xterm-256color"

[[hints.enabled]]
regex = '(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\S+'
hyperlinks = true
command = "google-chrome"
post_processing = true
mouse = { enabled = true, mods = "Control" }
binding = { key = "U", mods = "Control|Shift" }
